// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkzq-W_VmIvvMCYhmqawdxCfqQg2nJ0oU',
    appId: '1:1041294505377:web:5b7b145b269bb818b007e0',
    messagingSenderId: '1041294505377',
    projectId: 'rp-data-6668b',
    authDomain: 'rp-data-6668b.firebaseapp.com',
    storageBucket: 'rp-data-6668b.firebasestorage.app',
    measurementId: 'G-Q3914MNC3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNlKXnodDSiR2HdrzYRGyXtbDkcC0oo0',
    appId: '1:1041294505377:android:bf5440db530a05bbb007e0',
    messagingSenderId: '1041294505377',
    projectId: 'rp-data-6668b',
    storageBucket: 'rp-data-6668b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvTAgTWAU7UitLHTlUbOr-6QcWoJjGAk',
    appId: '1:1041294505377:ios:096713a903bef063b007e0',
    messagingSenderId: '1041294505377',
    projectId: 'rp-data-6668b',
    storageBucket: 'rp-data-6668b.firebasestorage.app',
    iosBundleId: 'com.example.retiredProfessionalsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxvTAgTWAU7UitLHTlUbOr-6QcWoJjGAk',
    appId: '1:1041294505377:ios:096713a903bef063b007e0',
    messagingSenderId: '1041294505377',
    projectId: 'rp-data-6668b',
    storageBucket: 'rp-data-6668b.firebasestorage.app',
    iosBundleId: 'com.example.retiredProfessionalsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkzq-W_VmIvvMCYhmqawdxCfqQg2nJ0oU',
    appId: '1:1041294505377:web:d0b27c174b14c6ffb007e0',
    messagingSenderId: '1041294505377',
    projectId: 'rp-data-6668b',
    authDomain: 'rp-data-6668b.firebaseapp.com',
    storageBucket: 'rp-data-6668b.firebasestorage.app',
    measurementId: 'G-ZT49MN6MYB',
  );
}
